name: "Run codecheck"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2    
      with: 
        python-version: 3.12
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install ruff
        pip list
    - name: Ruff check
      run: ruff check .
    - name: Ruff format
      run: ruff format .